# Generated by Django 4.2.11 on 2026-05-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('majors', '0001_initial'),
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الكلية')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور الكلية (الأصغر أولاً)', verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('publish_status', models.CharField(choices=[('published', 'منشور'), ('unpublished', 'غير منشور')], db_index=True, default='unpublished', help_text='المحتوى المنشور فقط يظهر للزوار', max_length=20, verbose_name='حالة النشر')),
                ('meta_title', models.CharField(blank=True, help_text='يظهر في نتائج البحث (60 حرف كحد أقصى)', max_length=60, verbose_name='عنوان SEO')),
                ('meta_description', models.TextField(blank=True, help_text='يظهر في نتائج البحث (160 حرف كحد أقصى)', max_length=160, verbose_name='وصف SEO')),
                ('focus_keyword', models.CharField(blank=True, help_text='الكلمة المفتاحية الرئيسية للصفحة', max_length=100, verbose_name='الكلمة المفتاحية')),
                ('canonical_url', models.URLField(blank=True, help_text='اتركه فارغاً لاستخدام الرابط الافتراضي', verbose_name='الرابط الأساسي')),
                ('robots_index', models.BooleanField(default=True, help_text='السماح لمحركات البحث بفهرسة هذه الصفحة', verbose_name='السماح بالفهرسة')),
                ('robots_follow', models.BooleanField(default=True, help_text='السماح لمحركات البحث بتتبع الروابط في هذه الصفحة', verbose_name='السماح بتتبع الروابط')),
                ('sitemap_include', models.BooleanField(default=True, help_text='تضمين هذه الصفحة في ملف sitemap.xml', verbose_name='تضمين في خريطة الموقع')),
                ('og_title', models.CharField(blank=True, help_text='العنوان عند المشاركة على وسائل التواصل', max_length=60, verbose_name='عنوان Open Graph')),
                ('og_description', models.TextField(blank=True, help_text='الوصف عند المشاركة على وسائل التواصل', max_length=160, verbose_name='وصف Open Graph')),
                ('og_image', models.ImageField(blank=True, help_text='الصورة عند المشاركة على وسائل التواصل (1200x630 بكسل)', upload_to='og_images/', verbose_name='صورة Open Graph')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='اسم الجامعة')),
                ('slug', models.SlugField(allow_unicode=True, help_text='رابط الصفحة (يدعم الأحرف العربية)', max_length=200, unique=True, verbose_name='الرابط')),
                ('logo', models.ImageField(help_text='شعار الجامعة (PNG مع خلفية شفافة مفضل)', upload_to='universities/logos/', verbose_name='شعار الجامعة')),
                ('main_image', models.ImageField(help_text='صورة رئيسية للجامعة', upload_to='universities/images/', verbose_name='الصورة الرئيسية')),
                ('description', models.TextField(help_text='وصف شامل عن الجامعة', verbose_name='الوصف')),
                ('location', models.CharField(help_text='موقع الجامعة (المدينة، الولاية)', max_length=200, verbose_name='الموقع')),
                ('video_url', models.URLField(blank=True, help_text='رابط فيديو YouTube أو Vimeo', verbose_name='رابط الفيديو')),
                ('admission_requirements', models.TextField(help_text='شروط القبول في الجامعة', verbose_name='شروط القبول')),
                ('registration_section', models.TextField(blank=True, help_text='معلومات عملية التسجيل والخطوات', verbose_name='قسم التسجيل')),
                ('related_articles', models.ManyToManyField(blank=True, related_name='universities', to='articles.article', verbose_name='المقالات المرتبطة')),
                ('related_majors', models.ManyToManyField(blank=True, related_name='universities', to='majors.major', verbose_name='التخصصات المرتبطة')),
            ],
            options={
                'verbose_name': 'جامعة',
                'verbose_name_plural': 'الجامعات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور السؤال (الأصغر أولاً)', verbose_name='ترتيب العرض')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='universities.university', verbose_name='الجامعة')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم البرنامج')),
                ('duration', models.CharField(help_text='مثال: 4 سنوات', max_length=100, verbose_name='مدة الدراسة')),
                ('tuition_fees', models.CharField(help_text='مثال: 20,000 رنجت ماليزي سنوياً', max_length=100, verbose_name='الرسوم الدراسية')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور البرنامج (الأصغر أولاً)', verbose_name='ترتيب العرض')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.faculty', verbose_name='الكلية')),
            ],
            options={
                'verbose_name': 'برنامج',
                'verbose_name_plural': 'البرامج',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='universities.university', verbose_name='الجامعة'),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('university', 'name')},
        ),
    ]
