# Generated by Django 4.2.11 on 2026-05-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['publish_status'], name='universitie_publish_86a17c_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['name'], name='universitie_name_504812_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['publish_status', 'name'], name='universitie_publish_83e28e_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['-created_at'], name='universitie_created_83ff81_idx'),
        ),
    ]
