# Generated by Django 4.2.11 on 2026-05-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_universitie_publish_86a17c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='university_type',
            field=models.CharField(choices=[('public', 'جامعة حكومية'), ('private', 'جامعة خاصة')], db_index=True, default='private', help_text='تصنيف الجامعة (حكومية أو خاصة)', max_length=20, verbose_name='نوع الجامعة'),
        ),
    ]
