# Generated by Django 4.2.11 on 2026-05-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_university_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(help_text='موقع الجامعة (المدينة، الولاية)', max_length=500, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='university',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط الفيديو'),
        ),
    ]
