# Generated by Django 4.2.11 on 2026-05-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_alter_university_location_alter_university_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.TextField(help_text='موقع الجامعة (المدينة، الولاية)', verbose_name='الموقع'),
        ),
    ]
