# Generated by Django 4.2.11 on 2026-05-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_alter_university_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='admission_requirements_bachelor',
            field=models.TextField(blank=True, default='', help_text='شروط القبول الخاصة ببرنامج البكالوريوس', verbose_name='شروط القبول للبكالوريوس (Bachelor’s)'),
        ),
        migrations.AddField(
            model_name='university',
            name='admission_requirements_master',
            field=models.TextField(blank=True, default='', help_text='شروط القبول الخاصة ببرنامج الماجستير', verbose_name='شروط القبول للماجستير (Master’s)'),
        ),
        migrations.AddField(
            model_name='university',
            name='admission_requirements_phd',
            field=models.TextField(blank=True, default='', help_text='شروط القبول الخاصة ببرنامج الدكتوراه', verbose_name='شروط القبول للدكتوراه (PhD)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='admission_requirements',
            field=models.TextField(blank=True, default='', help_text='شروط القبول العامة أو السابقة في الجامعة (أرشيف)', verbose_name='شروط القبول العامة / السابقة'),
        ),
    ]
