# Generated by Django 4.2.11 on 2026-05-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_university_admission_requirements_bachelor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='registration_section',
        ),
    ]
