# Generated by Django 4.2.11 on 2026-06-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_university_logo_alt_university_main_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.CharField(choices=[('kl', 'كوالالمبور'), ('selangor', 'سيلانجور'), ('penang', 'بينانج'), ('johor', 'جوهر')], db_index=True, default='kl', help_text='المدينة التي تقع بها الجامعة لتسهيل التصفية والبحث', max_length=20, verbose_name='المدينة'),
        ),
    ]
