# Generated by Django 4.2.11 on 2026-06-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0010_university_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(choices=[('kl', 'كوالالمبور'), ('selangor', 'سيلانجور'), ('penang', 'بينانج'), ('johor', 'جوهر'), ('kedah', 'قدح'), ('kelantan', 'كلنتان'), ('melaka', 'ملقا'), ('negeri-sembilan', 'نيجري سمبيلان'), ('pahang', 'باهانغ'), ('perak', 'بيرق'), ('perlis', 'برليس'), ('sabah', 'صباح'), ('sarawak', 'سراوق'), ('terengganu', 'ترينجانو'), ('putrajaya', 'بوتراجايا'), ('labuan', 'لابوان'), ('cyberjaya', 'سايبرجايا')], db_index=True, default='kl', help_text='المدينة التي تقع بها الجامعة لتسهيل التصفية والبحث', max_length=20, verbose_name='المدينة'),
        ),
    ]
