# Generated by Django 5.2.15 on 2026-06-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0012_alter_university_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='تفعيل هذا الخيار سيجعل الرابط مباشراً بدون بادئة الفئة (مثال: /slug/ بدلاً من /universities/slug/)', verbose_name='رابط قديم'),
        ),
    ]
