# Generated by Django 5.2.15 on 2026-06-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_is_legacy'),
        ('universities', '0014_alter_university_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='universities', to='articles.tag', verbose_name='الوسوم'),
        ),
    ]
