# Generated by Django 5.2.15 on 2026-06-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0016_university_keyphrase_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='telephone',
            field=models.CharField(blank=True, help_text='رقم هاتف التواصل للجامعة لتسهيل التواصل والبحث المحلي', max_length=50, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, help_text='رابط الموقع الإلكتروني الرسمي للجامعة (sameAs)', verbose_name='الموقع الرسمي للجامعة'),
        ),
    ]
