# Generated by Django 5.2.15 on 2026-06-29 19:12

from django.db import migrations, models

def populate_city_field(apps, schema_editor):
    University = apps.get_model('universities', 'University')
    
    STATE_CITIES_MAPPING = {
        'kl': ['kl'],
        'selangor': [
            'shah-alam', 'subang-jaya', 'kajang', 'petaling-jaya', 'serdang',
            'bangi', 'semenyih', 'klang', 'seri-kembangan', 'sungai-long',
            'bandar-sunway', 'damansara', 'gombak', 'saujana-putra', 'jenjarom',
            'other-selangor'
        ],
        'penang': ['georgetown', 'bayan-lepas', 'other-penang'],
        'johor': ['johor-bahru', 'skudai', 'batu-pahat', 'other-johor'],
        'kedah': ['alor-setar', 'sintok', 'other-kedah'],
        'kelantan': ['kota-bharu', 'other-kelantan'],
        'melaka': ['melaka', 'other-melaka'],
        'negeri-sembilan': ['nilai', 'seremban', 'other-negeri-sembilan'],
        'pahang': ['kuantan', 'gambang', 'other-pahang'],
        'perak': ['ipoh', 'kampar', 'tanjung-malim', 'seri-iskandar', 'other-perak'],
        'perlis': ['kangar', 'other-perlis'],
        'sabah': ['kota-kinabalu', 'other-sabah'],
        'sarawak': ['kuching', 'miri', 'other-sarawak'],
        'terengganu': ['kuala-terengganu', 'other-terengganu'],
        'putrajaya': ['putrajaya'],
        'labuan': ['victoria', 'labuan'],
        'cyberjaya': ['cyberjaya']
    }

    CITY_KEYWORDS = {
        'shah-alam': ['شاه علم', 'shah alam'],
        'subang-jaya': ['سوبانج جايا', 'سوبانغ جايا', 'subang jaya', 'subang'],
        'kajang': ['كاجانج', 'كاجانغ', 'kajang'],
        'petaling-jaya': ['بيتالينج جايا', 'بيتالينغ جايا', 'petaling jaya', 'pj'],
        'serdang': ['سردانج', 'سردانغ', 'serdang'],
        'bangi': ['بانجي', 'بانغي', 'bangi'],
        'semenyih': ['سيمينيه', 'semenyih'],
        'klang': ['كلانج', 'كلانغ', 'klang'],
        'seri-kembangan': ['سري كيمبانجان', 'سري كيمبانغان', 'seri kembangan'],
        'sungai-long': ['سونغاي لونغ', 'sungai long'],
        'bandar-sunway': ['بندر صنواي', 'صنواي', 'sunway'],
        'damansara': ['دامانسارا', 'دمنسارا', 'damansara'],
        'gombak': ['غومباك', 'جومباك', 'gombak'],
        'saujana-putra': ['سوجانا بوترا', 'saujana putra'],
        'jenjarom': ['جينجاروم', 'jenjarom'],
        'georgetown': ['جورج تاون', 'georgetown', 'george town'],
        'bayan-lepas': ['بايان ليباس', 'bayan lepas'],
        'johor-bahru': ['جوهر بهرو', 'جوهور بارو', 'johor bahru', 'jb'],
        'skudai': ['سكوداي', 'اسكوداي', 'skudai'],
        'batu-pahat': ['باتو باهات', 'batu phat', 'batu pahat'],
        'alor-setar': ['ألو سيتار', 'alor setar'],
        'sintok': ['سينتوت', 'sintok'],
        'kota-bharu': ['كوتابارو', 'kota bharu'],
        'nilai': ['نيلاي', 'nilai'],
        'seremban': ['سيريمبان', 'seremban'],
        'kuantan': ['كوانتان', 'kuantan'],
        'gambang': ['غامبانغ', 'gambang'],
        'ipoh': ['إيبوه', 'ipoh'],
        'kampar': ['كامبار', 'kampar'],
        'tanjung-malim': ['تانجونج ماليم', 'tanjung malim'],
        'seri-iskandar': ['سري اسكندر', 'seri iskandar'],
        'kangar': ['كانغار', 'kangar'],
        'kota-kinabalu': ['كوتا كينابالو', 'kota kinabalu'],
        'kuching': ['كوتشينغ', 'kuching'],
        'miri': ['ميري', 'miri'],
        'kuala-terengganu': ['كوالا تيرينجانو', 'kuala terengganu'],
        'victoria': ['فيكتوريا', 'victoria'],
        'labuan': ['لابوان', 'labuan'],
    }

    import re
    
    for uni in University.objects.all():
        state = uni.state
        if not state:
            state = 'kl'
            uni.state = state
            
        if state in ['kl', 'putrajaya', 'cyberjaya']:
            uni.city = state
            uni.save()
            continue
            
        location_text = uni.location or ''
        location_text_clean = re.sub(r'<[^>]+>', ' ', location_text).lower()
        
        detected_city = None
        possible_cities = STATE_CITIES_MAPPING.get(state, [])
        for city_slug in possible_cities:
            kws = CITY_KEYWORDS.get(city_slug, [])
            for kw in kws:
                if kw in location_text_clean or kw in uni.name.lower():
                    detected_city = city_slug
                    break
            if detected_city:
                break
                
        if not detected_city:
            if f'other-{state}' in possible_cities:
                detected_city = f'other-{state}'
            else:
                detected_city = possible_cities[0] if possible_cities else state
                
        uni.city = detected_city
        uni.save()

def rollback_city_field(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0018_universityattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='city',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='university',
            name='state',
            field=models.CharField(choices=[('kl', 'كوالالمبور'), ('selangor', 'سيلانجور'), ('penang', 'بينانج'), ('johor', 'جوهور'), ('kedah', 'قدح'), ('kelantan', 'كلنتان'), ('melaka', 'ملقا'), ('negeri-sembilan', 'نيجري سمبيلان'), ('pahang', 'باهانغ'), ('perak', 'بيرق'), ('perlis', 'برليس'), ('sabah', 'صباح'), ('sarawak', 'سراوق'), ('terengganu', 'ترينجانو'), ('putrajaya', 'بوتراجايا'), ('labuan', 'لابوان'), ('cyberjaya', 'سايبرجايا')], db_index=True, default='kl', help_text='الولاية التي تقع بها الجامعة لتسهيل التصفية والبحث', max_length=20, verbose_name='الولاية'),
        ),
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', help_text='المدينة التي تقع بها الجامعة لتسهيل التصفية والبحث', max_length=100, verbose_name='المدينة'),
        ),
        migrations.RunPython(populate_city_field, rollback_city_field),
    ]
