# Generated by Django 5.2.15 on 2026-06-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0020_alter_university_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='yearly_fees',
            field=models.JSONField(blank=True, help_text='رسوم كل سنة دراسية بشكل منفصل (اختياري). مثال: {"السنة الأولى": "5,424", "السنة الثانية": "4,964"}', null=True, verbose_name='الرسوم السنوية التفصيلية'),
        ),
    ]
