# Generated by Django 5.2.15 on 2026-07-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0021_program_yearly_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='one_time_fees',
            field=models.JSONField(blank=True, default=list, help_text='جداول الرسوم الإضافية التي تدفع مرة واحدة بصيغة JSON', verbose_name='رسوم تدفع مرة واحدة'),
        ),
    ]
