# Generated by Django 5.2.15 on 2026-07-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0015_salarytable_job_description_subjectstable_track_name_and_more'),
        ('universities', '0022_university_one_time_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='major',
            field=models.ForeignKey(blank=True, help_text='اختر التخصص العام المرتبط بهذا البرنامج (مثال: الوسائط المتعددة)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='majors.major', verbose_name='التخصص المرتبط'),
        ),
    ]
