# Generated by Django 5.2.15 on 2026-07-17 21:12

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0023_program_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityattachment',
            name='file',
            field=models.FileField(upload_to='universities/attachments/', validators=[apps.core.utils.validate_attachment_file], verbose_name='الملف'),
        ),
    ]
