# Generated by Django 5.2.15 on 2026-07-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0024_alter_universityattachment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['order', 'name'], 'verbose_name': 'جامعة', 'verbose_name_plural': 'الجامعات'},
        ),
        migrations.AddField(
            model_name='university',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='ترتيب ظهور الجامعة في صفحات القوائم (الأصغر أولاً)', verbose_name='ترتيب العرض'),
        ),
    ]
