# Generated by Django 4.2.26 on 2026-08-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("universities", "0025_alter_university_options_university_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="min_tuition_annual_usd",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="الحد الأدنى التقديري للرسوم السنوية بالدولار الأمريكي (USD) لعرضها في البطاقات ومقتطفات جوجل.",
                null=True,
                verbose_name="الحد الأدنى للرسوم السنوية بالدولار",
            ),
        ),
    ]
