# Generated by Django 4.2.11 on 2026-05-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('old_url', models.CharField(db_index=True, help_text='الرابط القديم الذي سيتم إعادة توجيهه', max_length=500, verbose_name='الرابط القديم')),
                ('new_url', models.CharField(help_text='الرابط الجديد الذي سيتم التوجيه إليه', max_length=500, verbose_name='الرابط الجديد')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='تفعيل أو تعطيل هذا التوجيه', verbose_name='نشط')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية عن سبب التوجيه', verbose_name='ملاحظات')),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='عدد المرات التي تم استخدام هذا التوجيه', verbose_name='عدد الزيارات')),
            ],
            options={
                'verbose_name': 'إعادة توجيه',
                'verbose_name_plural': 'إعادات التوجيه',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['old_url', 'is_active'], name='redirects_r_old_url_e4a4cf_idx')],
            },
        ),
    ]
