# Generated by Django 4.2.11 on 2026-05-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='طھط§ط±ظٹط® ط§ظ„ط¥ظ†ط´ط§ط،'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='طھط§ط±ظٹط® ط§ظ„طھط\xadط¯ظٹط«'),
        ),
    ]
