# Generated by Django 5.2.15 on 2026-07-12 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500, verbose_name='رابط الاستيراد')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع المحتوى')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='نسبة التقدم')),
                ('status_message', models.CharField(blank=True, max_length=500, verbose_name='رسالة الحالة')),
                ('result_url', models.CharField(blank=True, max_length=500, verbose_name='رابط النتيجة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عملية استيراد',
                'verbose_name_plural': 'عمليات الاستيراد',
                'ordering': ['-created_at'],
            },
        ),
    ]
