# Generated by Django 4.2.11 on 2026-05-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('publish_status', models.CharField(choices=[('published', 'منشور'), ('unpublished', 'غير منشور')], db_index=True, default='unpublished', help_text='المحتوى المنشور فقط يظهر للزوار', max_length=20, verbose_name='حالة النشر')),
                ('meta_title', models.CharField(blank=True, help_text='يظهر في نتائج البحث (60 حرف كحد أقصى)', max_length=60, verbose_name='عنوان SEO')),
                ('meta_description', models.TextField(blank=True, help_text='يظهر في نتائج البحث (160 حرف كحد أقصى)', max_length=160, verbose_name='وصف SEO')),
                ('focus_keyword', models.CharField(blank=True, help_text='الكلمة المفتاحية الرئيسية للصفحة', max_length=100, verbose_name='الكلمة المفتاحية')),
                ('canonical_url', models.URLField(blank=True, help_text='اتركه فارغاً لاستخدام الرابط الافتراضي', verbose_name='الرابط الأساسي')),
                ('robots_index', models.BooleanField(default=True, help_text='السماح لمحركات البحث بفهرسة هذه الصفحة', verbose_name='السماح بالفهرسة')),
                ('robots_follow', models.BooleanField(default=True, help_text='السماح لمحركات البحث بتتبع الروابط في هذه الصفحة', verbose_name='السماح بتتبع الروابط')),
                ('sitemap_include', models.BooleanField(default=True, help_text='تضمين هذه الصفحة في ملف sitemap.xml', verbose_name='تضمين في خريطة الموقع')),
                ('og_title', models.CharField(blank=True, help_text='العنوان عند المشاركة على وسائل التواصل', max_length=60, verbose_name='عنوان Open Graph')),
                ('og_description', models.TextField(blank=True, help_text='الوصف عند المشاركة على وسائل التواصل', max_length=160, verbose_name='وصف Open Graph')),
                ('og_image', models.ImageField(blank=True, help_text='الصورة عند المشاركة على وسائل التواصل (1200x630 بكسل)', upload_to='og_images/', verbose_name='صورة Open Graph')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='اسم التخصص')),
                ('slug', models.SlugField(allow_unicode=True, help_text='رابط الصفحة (يدعم الأحرف العربية)', max_length=200, unique=True, verbose_name='الرابط')),
                ('main_image', models.ImageField(upload_to='majors/images/', verbose_name='الصورة الرئيسية')),
                ('description', models.TextField(help_text='وصف شامل عن التخصص', verbose_name='الوصف')),
                ('study_duration', models.CharField(help_text='مثال: 4 سنوات', max_length=100, verbose_name='مدة الدراسة')),
                ('tuition_fees', models.CharField(blank=True, help_text='مثال: 15,000 - 25,000 رنجت سنوياً', max_length=100, verbose_name='الرسوم الدراسية')),
                ('study_language', models.CharField(blank=True, help_text='مثال: الإنجليزية', max_length=100, verbose_name='لغة الدراسة')),
                ('practical_training', models.CharField(blank=True, help_text='مثال: متاح في السنة الأخيرة', max_length=200, verbose_name='التدريب العملي')),
                ('career_opportunities', models.TextField(blank=True, help_text='فرص العمل المتاحة بعد التخرج', verbose_name='فرص العمل')),
                ('why_study_section', models.TextField(blank=True, help_text='أسباب دراسة هذا التخصص', verbose_name='لماذا تدرس هذا التخصص')),
                ('how_to_apply_section', models.TextField(blank=True, help_text='خطوات التقديم للتخصص', verbose_name='كيفية التقديم')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'التخصصات',
                'ordering': ['name'],
            },
        ),
    ]
