# Generated by Django 4.2.11 on 2026-05-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0003_initial'),
        ('majors', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='best_universities',
            field=models.ManyToManyField(blank=True, related_name='best_majors', to='universities.university', verbose_name='أفضل الجامعات'),
        ),
        migrations.AddField(
            model_name='major',
            name='cheap_universities',
            field=models.ManyToManyField(blank=True, related_name='cheap_majors', to='universities.university', verbose_name='الجامعات الاقتصادية'),
        ),
        migrations.AddField(
            model_name='major',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='majors', to='articles.article', verbose_name='المقالات المرتبطة'),
        ),
    ]
