# Generated by Django 4.2.11 on 2026-05-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='مثال: السنة الأولى', max_length=100, verbose_name='السنة الدراسية')),
                ('subjects', models.TextField(help_text='المواد الدراسية (يمكن فصلها بفواصل)', verbose_name='المواد')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور الصف (الأصغر أولاً)', verbose_name='ترتيب العرض')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_tables', to='majors.major', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'جدول المواد',
                'verbose_name_plural': 'جداول المواد',
                'ordering': ['sort_order', 'academic_year'],
            },
        ),
        migrations.CreateModel(
            name='SalaryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='مثال: مهندس برمجيات', max_length=200, verbose_name='المسمى الوظيفي')),
                ('average_monthly_salary', models.CharField(help_text='مثال: 5,000 - 8,000 رنجت ماليزي', max_length=100, verbose_name='متوسط الراتب الشهري')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور الصف (الأصغر أولاً)', verbose_name='ترتيب العرض')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_tables', to='majors.major', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'جدول الرواتب',
                'verbose_name_plural': 'جداول الرواتب',
                'ordering': ['sort_order', 'job_title'],
            },
        ),
        migrations.CreateModel(
            name='CountriesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(help_text='مثال: ماليزيا', max_length=200, verbose_name='الوجهة')),
                ('study_duration', models.CharField(help_text='مثال: 4 سنوات', max_length=100, verbose_name='مدة الدراسة')),
                ('annual_fees', models.CharField(help_text='مثال: 20,000 - 30,000 رنجت ماليزي', max_length=100, verbose_name='الرسوم السنوية')),
                ('living_cost', models.CharField(help_text='مثال: 1,500 - 2,500 رنجت ماليزي شهرياً', max_length=100, verbose_name='تكلفة المعيشة')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور الصف (الأصغر أولاً)', verbose_name='ترتيب العرض')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_tables', to='majors.major', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'جدول الدول',
                'verbose_name_plural': 'جداول الدول',
                'ordering': ['sort_order', 'destination'],
            },
        ),
    ]
