# Generated by Django 4.2.11 on 2026-05-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0003_subjectstable_salarytable_countriestable'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['publish_status'], name='majors_majo_publish_161a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['name'], name='majors_majo_name_eb7cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['publish_status', 'name'], name='majors_majo_publish_24dfc2_idx'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['-created_at'], name='majors_majo_created_93a2a2_idx'),
        ),
    ]
