# Generated by Django 4.2.11 on 2026-05-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0004_major_majors_majo_publish_161a7b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='bachelor_duration',
            field=models.CharField(blank=True, help_text='مثال: 4 سنوات', max_length=100, verbose_name='مدة البكالوريوس'),
        ),
        migrations.AddField(
            model_name='major',
            name='major_category',
            field=models.CharField(choices=[('medical', 'التخصصات الطبية'), ('engineering', 'التخصصات الهندسية'), ('cs', 'الحاسوب والتكنولوجيا'), ('business', 'إدارة الأعمال'), ('science', 'العلوم'), ('other', 'تخصصات أخرى')], db_index=True, default='other', help_text='تصنيف التخصص حسب المجال', max_length=20, verbose_name='فئة التخصص'),
        ),
        migrations.AddField(
            model_name='major',
            name='master_duration',
            field=models.CharField(blank=True, help_text='مثال: سنتان', max_length=100, verbose_name='مدة الماجستير'),
        ),
        migrations.AddField(
            model_name='major',
            name='phd_duration',
            field=models.CharField(blank=True, help_text='مثال: 3-4 سنوات', max_length=100, verbose_name='مدة الدكتوراه'),
        ),
        migrations.AlterField(
            model_name='major',
            name='study_duration',
            field=models.CharField(help_text='مثال: 4 سنوات (سيتم استبدالها بالحقول المفصلة أدناه)', max_length=100, verbose_name='مدة الدراسة (عام)'),
        ),
    ]
