# Generated by Django 4.2.11 on 2026-05-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0005_major_bachelor_duration_major_major_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='seo_critical_count',
            field=models.PositiveIntegerField(default=0, verbose_name='الأخطاء الحرجة'),
        ),
        migrations.AddField(
            model_name='major',
            name='seo_grade',
            field=models.CharField(default='needs_improvement', max_length=20, verbose_name='تقييم SEO'),
        ),
        migrations.AddField(
            model_name='major',
            name='seo_last_analysis',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تحليل'),
        ),
        migrations.AddField(
            model_name='major',
            name='seo_score',
            field=models.PositiveIntegerField(default=0, verbose_name='درجة SEO'),
        ),
        migrations.AddField(
            model_name='major',
            name='seo_warning_count',
            field=models.PositiveIntegerField(default=0, verbose_name='التحذيرات'),
        ),
        migrations.AlterField(
            model_name='major',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='ط§طھط±ظƒظ‡ ظپط§ط±ط؛ط§ظ‹ ظ„ط§ط³طھط®ط¯ط§ظ… ط§ظ„ط±ط§ط¨ط· ط§ظ„ط§ظپطھط±ط§ط¶ظٹ', verbose_name='ط§ظ„ط±ط§ط¨ط· ط§ظ„ط£ط³ط§ط³ظٹ'),
        ),
        migrations.AlterField(
            model_name='major',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='طھط§ط±ظٹط® ط§ظ„ط¥ظ†ط´ط§ط،'),
        ),
        migrations.AlterField(
            model_name='major',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='ط§ظ„ظƒظ„ظ…ط© ط§ظ„ظ…ظپطھط§ط\xadظٹط© ط§ظ„ط±ط¦ظٹط³ظٹط© ظ„ظ„طµظپط\xadط©', max_length=100, verbose_name='ط§ظ„ظƒظ„ظ…ط© ط§ظ„ظ…ظپطھط§ط\xadظٹط©'),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_category',
            field=models.CharField(choices=[('medical', 'التخصصات الطبية'), ('engineering', 'التخصصات الهندسية'), ('cs', 'الحاسوب والتكنولوجيا'), ('business', 'إدارة الأعمال'), ('science', 'العلوم'), ('other', 'تخصصات أخرى')], db_index=True, default='other', help_text='تصنيف التخصص حسب المجال', max_length=20, verbose_name='تصنيف التخصص'),
        ),
        migrations.AlterField(
            model_name='major',
            name='meta_description',
            field=models.TextField(blank=True, help_text='ظٹط¸ظ‡ط± ظپظٹ ظ†طھط§ط¦ط¬ ط§ظ„ط¨ط\xadط« (160 ط\xadط±ظپ ظƒط\xadط¯ ط£ظ‚طµظ‰)', max_length=160, verbose_name='ظˆطµظپ SEO'),
        ),
        migrations.AlterField(
            model_name='major',
            name='meta_title',
            field=models.CharField(blank=True, help_text='ظٹط¸ظ‡ط± ظپظٹ ظ†طھط§ط¦ط¬ ط§ظ„ط¨ط\xadط« (60 ط\xadط±ظپ ظƒط\xadط¯ ط£ظ‚طµظ‰)', max_length=60, verbose_name='ط¹ظ†ظˆط§ظ† SEO'),
        ),
        migrations.AlterField(
            model_name='major',
            name='og_description',
            field=models.TextField(blank=True, help_text='ط§ظ„ظˆطµظپ ط¹ظ†ط¯ ط§ظ„ظ…ط´ط§ط±ظƒط© ط¹ظ„ظ‰ ظˆط³ط§ط¦ظ„ ط§ظ„طھظˆط§طµظ„', max_length=160, verbose_name='ظˆطµظپ Open Graph'),
        ),
        migrations.AlterField(
            model_name='major',
            name='og_image',
            field=models.ImageField(blank=True, help_text='ط§ظ„طµظˆط±ط© ط¹ظ†ط¯ ط§ظ„ظ…ط´ط§ط±ظƒط© ط¹ظ„ظ‰ ظˆط³ط§ط¦ظ„ ط§ظ„طھظˆط§طµظ„ (1200x630 ط¨ظƒط³ظ„)', upload_to='og_images/', verbose_name='طµظˆط±ط© Open Graph'),
        ),
        migrations.AlterField(
            model_name='major',
            name='og_title',
            field=models.CharField(blank=True, help_text='ط§ظ„ط¹ظ†ظˆط§ظ† ط¹ظ†ط¯ ط§ظ„ظ…ط´ط§ط±ظƒط© ط¹ظ„ظ‰ ظˆط³ط§ط¦ظ„ ط§ظ„طھظˆط§طµظ„', max_length=60, verbose_name='ط¹ظ†ظˆط§ظ† Open Graph'),
        ),
        migrations.AlterField(
            model_name='major',
            name='publish_status',
            field=models.CharField(choices=[('published', 'ظ…ظ†ط´ظˆط±'), ('unpublished', 'ط؛ظٹط± ظ…ظ†ط´ظˆط±')], db_index=True, default='unpublished', help_text='ط§ظ„ظ…ط\xadطھظˆظ‰ ط§ظ„ظ…ظ†ط´ظˆط± ظپظ‚ط· ظٹط¸ظ‡ط± ظ„ظ„ط²ظˆط§ط±', max_length=20, verbose_name='ط\xadط§ظ„ط© ط§ظ„ظ†ط´ط±'),
        ),
        migrations.AlterField(
            model_name='major',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='ط§ظ„ط³ظ…ط§ط\xad ظ„ظ…ط\xadط±ظƒط§طھ ط§ظ„ط¨ط\xadط« ط¨طھطھط¨ط¹ ط§ظ„ط±ظˆط§ط¨ط· ظپظٹ ظ‡ط°ظ‡ ط§ظ„طµظپط\xadط©', verbose_name='ط§ظ„ط³ظ…ط§ط\xad ط¨طھطھط¨ط¹ ط§ظ„ط±ظˆط§ط¨ط·'),
        ),
        migrations.AlterField(
            model_name='major',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='ط§ظ„ط³ظ…ط§ط\xad ظ„ظ…ط\xadط±ظƒط§طھ ط§ظ„ط¨ط\xadط« ط¨ظپظ‡ط±ط³ط© ظ‡ط°ظ‡ ط§ظ„طµظپط\xadط©', verbose_name='ط§ظ„ط³ظ…ط§ط\xad ط¨ط§ظ„ظپظ‡ط±ط³ط©'),
        ),
        migrations.AlterField(
            model_name='major',
            name='sitemap_include',
            field=models.BooleanField(default=True, help_text='طھط¶ظ…ظٹظ† ظ‡ط°ظ‡ ط§ظ„طµظپط\xadط© ظپظٹ ظ…ظ„ظپ sitemap.xml', verbose_name='طھط¶ظ…ظٹظ† ظپظٹ ط®ط±ظٹط·ط© ط§ظ„ظ…ظˆظ‚ط¹'),
        ),
        migrations.AlterField(
            model_name='major',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='طھط§ط±ظٹط® ط§ظ„طھط\xadط¯ظٹط«'),
        ),
    ]
