# Generated by Django 4.2.11 on 2026-06-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0007_major_main_image_alt_alter_major_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='meta_title',
            field=models.CharField(blank=True, help_text='يظهر في نتائج البحث (150 حرف كحد أقصى)', max_length=150, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='major',
            name='og_title',
            field=models.CharField(blank=True, help_text='العنوان عند المشاركة على وسائل التواصل', max_length=150, verbose_name='عنوان Open Graph'),
        ),
    ]
