# Generated by Django 5.2.15 on 2026-07-02 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0010_major_keyphrase_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_category',
            field=models.CharField(choices=[('medical', 'التخصصات الطبية'), ('engineering', 'التخصصات الهندسية'), ('cs', 'الحاسوب والتكنولوجيا'), ('business', 'إدارة الأعمال'), ('science', 'العلوم'), ('other', 'تخصصات أخرى')], db_index=True, default='other', help_text='تصنيف التخصص حسب المجال (قيمة قديمة لتوافق البيانات)', max_length=20, verbose_name='تصنيف التخصص (القديم)'),
        ),
        migrations.CreateModel(
            name='MajorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(allow_unicode=True, help_text='رابط التصنيف (يدعم الأحرف العربية)', max_length=200, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, help_text='وصف التصنيف', verbose_name='الوصف')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='majors.majorcategory', verbose_name='التصنيف الأب')),
            ],
            options={
                'verbose_name': 'تصنيف تخصص',
                'verbose_name_plural': 'تصنيفات التخصصات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='major',
            name='category',
            field=models.ForeignKey(blank=True, help_text='التصنيف الهرمي للتخصص', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majors', to='majors.majorcategory', verbose_name='التصنيف الجديد'),
        ),
        migrations.AddIndex(
            model_name='majorcategory',
            index=models.Index(fields=['name'], name='majors_majo_name_0aeff5_idx'),
        ),
        migrations.AddIndex(
            model_name='majorcategory',
            index=models.Index(fields=['slug'], name='majors_majo_slug_96d66f_idx'),
        ),
    ]
