# Generated by Django 5.2.15 on 2026-07-02 02:09

from django.db import migrations

def seed_categories_and_migrate_majors(apps, schema_editor):
    MajorCategory = apps.get_model('majors', 'MajorCategory')
    Major = apps.get_model('majors', 'Major')
    
    # Define categories structure
    hierarchy = {
        'الطب والصحة': [
            'طب الاسنان',
            'دراسة الصيدلة',
            'الطب البشري',
            'الصحة العامة',
            'دراسة التمريض',
            'العلاج الطبيعي',
            'تخصص البصريات'
        ],
        'الهندسة': [
            'الهندسة الكيميائية',
            'هندسة الروبوتات',
            'النانو تكنولوجي',
            'الهندسة الطبية',
            'الهندسة الإلكترونية',
            'الهندسة الصناعية',
            'هندسة الميكاترونيك',
            'الهندسة المدنية',
            'هندسة الاتصالات',
            'هندسة المعدات الطبية',
            'الهندسة المعمارية',
            'الهندسة النووية',
            'الهندسة الميكانيكية',
            'هندسة البترول',
            'الهندسة الكهربائية'
        ],
        'علوم الحاسوب': [
            'الذكاء الاصطناعي',
            'علوم الحاسوب',
            'علوم البيانات',
            'الأمن السيبراني',
            'هندسة البرمجيات',
            'تكنولوجيا المعلومات'
        ],
        'العلوم الادارية والاقتصادية': [
            'الفندقة والسياحة',
            'اللوجستيات وسلسلة التوريد',
            'ادارة الاعمال',
            'الهندسة المالية',
            'علوم مالية ومصرفية',
            'التجارة الإلكترونية',
            'المحاسبة',
            'الاقتصاد',
            'التسويق'
        ],
        'الفنون والتصميم': [
            'تصميم الجرافيك',
            'الموسيقى',
            'تصميم الأزياء',
            'الرسوم المتحركة',
            'إنتاج الأفلام والفيديو'
        ],
        'الاداب والعلوم': [
            'دراسة علم النفس',
            'الاتصال الجماهيري',
            'دراسة العلاقات الدولية',
            'العلوم الرياضية',
            'اللغة الانجليزية',
            'علم الأحياء',
            'العلاقات العامة',
            'العلوم البيئية'
        ],
        'القانون': [],
        'التخصصات عن بعد في ماليزيا': [],
        'الوسائط المتعددة': [],
        'السنة التحضيرية': []
    }

    import re
    def get_slug(name):
        s = name.replace(' ', '-').replace('/', '-').replace('&', '-').replace('\\', '-')
        s = re.sub(r'[^\w\s-]', '', s)
        s = re.sub(r'-+', '-', s)
        return s.strip('-').lower()

    created_categories = {}
    
    for parent_name, children in hierarchy.items():
        parent_slug = get_slug(parent_name)
        
        # Avoid duplicate slug for cs child
        if parent_name == 'علوم الحاسوب':
            parent_slug = 'علوم-الحاسوب-فئة'
            
        parent_cat, _ = MajorCategory.objects.get_or_create(
            name=parent_name,
            defaults={'slug': parent_slug}
        )
        created_categories[parent_name] = parent_cat
        
        for child_name in children:
            child_slug = get_slug(child_name)
            if child_name == 'علوم الحاسوب':
                child_slug = 'علوم-الحاسوب' # Let the child have the main slug
            
            child_cat, _ = MajorCategory.objects.get_or_create(
                name=child_name,
                defaults={
                    'slug': child_slug,
                    'parent': parent_cat
                }
            )
            created_categories[child_name] = child_cat

    # Let's map old major_category choices to new MajorCategory
    mapping = {
        'medical': created_categories['الطب والصحة'],
        'engineering': created_categories['الهندسة'],
        'cs': created_categories['علوم الحاسوب'],
        'business': created_categories['العلوم الادارية والاقتصادية'],
        'science': created_categories['الاداب والعلوم'],
        'other': created_categories['الوسائط المتعددة']
    }

    for major in Major.objects.all():
        old_cat = major.major_category
        matched_cat = None
        
        # Check all child categories first
        for cat_name, cat_obj in created_categories.items():
            if cat_obj.parent and cat_name in major.name:
                matched_cat = cat_obj
                break
        
        if not matched_cat:
            matched_cat = mapping.get(old_cat, mapping['other'])
            
        major.category = matched_cat
        major.save()

def rollback_categories(apps, schema_editor):
    MajorCategory = apps.get_model('majors', 'MajorCategory')
    MajorCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0011_alter_major_major_category_majorcategory_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_categories_and_migrate_majors, rollback_categories),
    ]
