# Generated by Django 5.2.15 on 2026-07-02 02:20

from django.db import migrations

def sync_categories(apps, schema_editor):
    MajorCategory = apps.get_model('majors', 'MajorCategory')
    Major = apps.get_model('majors', 'Major')
    
    # 1. Define the exact 11 target categories requested by the user
    target_names = [
        'الطب و الصحة',
        'الهندسة',
        'علوم الحاسوب',
        'العلوم الادارية و الاقتصادية',
        'الفنون و التصميم',
        'الاداب و العلوم',
        'العلاقات العامة',
        'القانون',
        'التخصصات عن بعد في ماليزيا',
        'الوسائط المتعددة',
        'السنة التحضيرية'
    ]
    
    import re
    def get_slug(name):
        s = name.replace(' ', '-').replace('/', '-').replace('&', '-').replace('\\', '-')
        s = re.sub(r'[^\w\s-]', '', s)
        s = re.sub(r'-+', '-', s)
        return s.strip('-').lower()

    # Create/update the 11 flat categories
    created_categories = {}
    kept_ids = set()
    for name in target_names:
        slug = get_slug(name)
        cat, created = MajorCategory.objects.get_or_create(
            name=name,
            defaults={'slug': slug, 'parent': None}
        )
        if not created:
            cat.parent = None
            cat.slug = slug
            cat.save()
        created_categories[name] = cat
        kept_ids.add(cat.id)

    # 2. Map existing majors to the new 11 flat categories based on keywords and fallback
    mapping_old = {
        'medical': created_categories['الطب و الصحة'],
        'engineering': created_categories['الهندسة'],
        'cs': created_categories['علوم الحاسوب'],
        'business': created_categories['العلوم الادارية و الاقتصادية'],
        'science': created_categories['الاداب و العلوم'],
        'other': created_categories['الوسائط المتعددة']
    }
    
    for major in Major.objects.all():
        name_lower = major.name.lower()
        matched_cat = None
        
        # Keyword-based mapping to the 11 categories
        if any(w in name_lower for w in ['طب', 'صيدلة', 'تمريض', 'علاج طبيعي', 'بصريات']):
            matched_cat = created_categories['الطب و الصحة']
        elif 'علاقات عامة' in name_lower or 'العلاقات العامة' in name_lower:
            matched_cat = created_categories['العلاقات العامة']
        elif 'هندسة' in name_lower and not any(w in name_lower for w in ['برمجيات', 'مالية']):
            matched_cat = created_categories['الهندسة']
        elif any(w in name_lower for w in ['حاسوب', 'ذكاء اصطناعي', 'بيانات', 'أمن سيبراني', 'برمجيات', 'تكنولوجيا المعلومات']):
            matched_cat = created_categories['علوم الحاسوب']
        elif any(w in name_lower for w in ['فندقة', 'سياحة', 'لوجستيات', 'أعمال', 'مالية', 'تجارة', 'محاسبة', 'اقتصاد', 'تسويق']):
            matched_cat = created_categories['العلوم الادارية و الاقتصادية']
        elif any(w in name_lower for w in ['تصميم', 'موسيقى', 'أزياء', 'رسوم متحركة', 'أفلام', 'فيديو']):
            matched_cat = created_categories['الفنون و التصميم']
        elif any(w in name_lower for w in ['نفس', 'اتصال', 'علاقات دولية', 'رياضية', 'انجليزية', 'أحياء', 'بيئية']):
            matched_cat = created_categories['الاداب و العلوم']
        elif 'قانون' in name_lower:
            matched_cat = created_categories['القانون']
        elif 'عن بعد' in name_lower:
            matched_cat = created_categories['التخصصات عن بعد في ماليزيا']
        elif 'وسائط' in name_lower:
            matched_cat = created_categories['الوسائط المتعددة']
        elif 'تحضيرية' in name_lower:
            matched_cat = created_categories['السنة التحضيرية']
            
        if not matched_cat:
            # Fallback to old major_category mapping
            matched_cat = mapping_old.get(major.major_category, created_categories['الوسائط المتعددة'])
            
        major.category = matched_cat
        major.save()

    # 3. Clean up: delete all other categories
    invalid_cats = MajorCategory.objects.exclude(id__in=kept_ids)
    invalid_cats.delete()

def rollback_sync_categories(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0012_auto_20260702_0509'),
    ]

    operations = [
        migrations.RunPython(sync_categories, rollback_sync_categories),
    ]
