# Generated by Django 5.2.15 on 2026-07-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0013_clean_and_sync_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorcategory',
            name='parent',
        ),
    ]
