# Generated by Django 5.2.15 on 2026-07-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0014_remove_parent_from_majorcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytable',
            name='job_description',
            field=models.TextField(blank=True, default='', help_text='مثال: تصميم التطبيقات وتجربة المستخدم', verbose_name='طبيعة العمل'),
        ),
        migrations.AddField(
            model_name='subjectstable',
            name='track_name',
            field=models.CharField(blank=True, default='', help_text='مثال: الرسوم المتحركة أو المؤثرات البصرية (اتركه فارغاً للتخصص العام)', max_length=200, verbose_name='المسار/التخصص الفرعي'),
        ),
        migrations.CreateModel(
            name='MajorAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الملف')),
                ('file', models.FileField(upload_to='majors/attachments/', verbose_name='الملف')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='majors.major', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'ملف التخصص',
                'verbose_name_plural': 'ملفات التخصص',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MajorFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور السؤال (الأصغر أولاً)', verbose_name='ترتيب العرض')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='majors.major', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'سؤال شائع للتخصص',
                'verbose_name_plural': 'الأسئلة الشائعة للتخصص',
                'ordering': ['sort_order'],
            },
        ),
    ]
