# Generated by Django 5.2.15 on 2026-07-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0015_salarytable_job_description_subjectstable_track_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countriestable',
            name='annual_fees',
            field=models.CharField(help_text='مثال: 20,000 - 30,000 رنجت ماليزي', max_length=500, verbose_name='الرسوم السنوية'),
        ),
        migrations.AlterField(
            model_name='countriestable',
            name='destination',
            field=models.CharField(help_text='مثال: ماليزيا', max_length=500, verbose_name='الوجهة'),
        ),
        migrations.AlterField(
            model_name='countriestable',
            name='living_cost',
            field=models.CharField(help_text='مثال: 1,500 - 2,500 رنجت ماليزي شهرياً', max_length=500, verbose_name='تكلفة المعيشة'),
        ),
        migrations.AlterField(
            model_name='countriestable',
            name='study_duration',
            field=models.CharField(help_text='مثال: 4 سنوات', max_length=500, verbose_name='مدة الدراسة'),
        ),
        migrations.AlterField(
            model_name='major',
            name='bachelor_duration',
            field=models.CharField(blank=True, help_text='مثال: 4 سنوات', max_length=500, verbose_name='مدة البكالوريوس'),
        ),
        migrations.AlterField(
            model_name='major',
            name='master_duration',
            field=models.CharField(blank=True, help_text='مثال: سنتان', max_length=500, verbose_name='مدة الماجستير'),
        ),
        migrations.AlterField(
            model_name='major',
            name='phd_duration',
            field=models.CharField(blank=True, help_text='مثال: 3-4 سنوات', max_length=500, verbose_name='مدة الدكتوراه'),
        ),
        migrations.AlterField(
            model_name='major',
            name='practical_training',
            field=models.CharField(blank=True, help_text='مثال: متاح في السنة الأخيرة', max_length=500, verbose_name='التدريب العملي'),
        ),
        migrations.AlterField(
            model_name='major',
            name='study_duration',
            field=models.TextField(help_text='مثال: 4 سنوات (سيتم استبدالها بالحقول المفصلة أدناه)', verbose_name='مدة الدراسة (عام)'),
        ),
        migrations.AlterField(
            model_name='major',
            name='study_language',
            field=models.TextField(blank=True, default='', help_text='مثال: الإنجليزية', verbose_name='لغة الدراسة'),
        ),
        migrations.AlterField(
            model_name='major',
            name='tuition_fees',
            field=models.TextField(blank=True, default='', help_text='مثال: 15,000 - 25,000 رنجت سنوياً', verbose_name='الرسوم الدراسية'),
        ),
        migrations.AlterField(
            model_name='salarytable',
            name='average_monthly_salary',
            field=models.CharField(help_text='مثال: 5,000 - 8,000 رنجت ماليزي', max_length=500, verbose_name='متوسط الراتب الشهري'),
        ),
        migrations.AlterField(
            model_name='salarytable',
            name='job_title',
            field=models.CharField(help_text='مثال: مهندس برمجيات', max_length=500, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='subjectstable',
            name='academic_year',
            field=models.CharField(help_text='مثال: السنة الأولى', max_length=500, verbose_name='السنة الدراسية'),
        ),
        migrations.AlterField(
            model_name='subjectstable',
            name='track_name',
            field=models.CharField(blank=True, default='', help_text='مثال: الرسوم المتحركة أو المؤثرات البصرية (اتركه فارغاً للتخصص العام)', max_length=500, verbose_name='المسار/التخصص الفرعي'),
        ),
    ]
