# Generated by Django 5.2.15 on 2026-07-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_keyphrase_synonyms'),
        ('majors', '0017_alter_major_tuition_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='majors', to='articles.tag', verbose_name='الوسوم'),
        ),
    ]
