# Generated by Django 5.2.15 on 2026-07-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0018_major_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='competitor_url',
            field=models.URLField(blank=True, help_text='رابط صفحة التخصص المستخدمة لدمج البيانات من موقع المنافس', max_length=500, verbose_name='رابط التخصص عند المنافس'),
        ),
    ]
