# Generated by Django 5.2.15 on 2026-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0019_major_competitor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='study_duration',
            field=models.TextField(blank=True, help_text='مثال: 4 سنوات (سيتم استبدالها بالحقول المفصلة أدناه)', verbose_name='مدة الدراسة (عام)'),
        ),
    ]
