# Generated by Django 5.2.15 on 2026-07-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0020_alter_major_study_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'تصنيف تخصص', 'verbose_name_plural': 'تصنيفات التخصصات'},
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='ترتيب ظهور التصنيف (الأصغر أولاً)', verbose_name='ترتيب العرض'),
        ),
        migrations.AddIndex(
            model_name='majorcategory',
            index=models.Index(fields=['sort_order'], name='majors_majo_sort_or_394ed3_idx'),
        ),
    ]
