# Generated by Django 5.2.15 on 2026-07-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0021_alter_majorcategory_options_majorcategory_sort_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='tuition_fees',
        ),
    ]
