# Generated by Django 5.2.15 on 2026-07-17 21:12

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0022_remove_major_tuition_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorattachment',
            name='file',
            field=models.FileField(upload_to='majors/attachments/', validators=[apps.core.utils.validate_attachment_file], verbose_name='الملف'),
        ),
    ]
