# Generated by Django 5.2.15 on 2026-07-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0023_alter_majorattachment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='major',
            options={'ordering': ['order', 'name'], 'verbose_name': 'تخصص', 'verbose_name_plural': 'التخصصات'},
        ),
        migrations.AddField(
            model_name='major',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='ترتيب ظهور التخصص في صفحات القوائم (الأصغر أولاً)', verbose_name='ترتيب العرض'),
        ),
    ]
