# Generated by Django 4.2.11 on 2026-05-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_steps_title', models.CharField(default='خطوات التسجيل', help_text='العنوان الذي يظهر في جميع صفحات الجامعات', max_length=200, verbose_name='عنوان قسم خطوات التسجيل')),
                ('registration_steps_content', models.TextField(blank=True, help_text='محتوى HTML يظهر في جميع صفحات الجامعات (يدعم HTML)', verbose_name='محتوى خطوات التسجيل')),
                ('site_name', models.CharField(default='بوابات العلوم', max_length=200, verbose_name='اسم الموقع')),
                ('site_description', models.TextField(blank=True, verbose_name='وصف الموقع')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='رقم WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
