# Generated by Django 4.2.11 on 2026-05-30 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ظ…ظˆظ‚ط¹', 'verbose_name_plural': 'ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ظ…ظˆظ‚ط¹'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'ظ…ظ„ظپ ط§ظ„ظ…ط³طھط®ط¯ظ…', 'verbose_name_plural': 'ظ…ظ„ظپط§طھ ط§ظ„ظ…ط³طھط®ط¯ظ…ظٹظ†'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='طھط§ط±ظٹط® ط§ظ„ط¥ظ†ط´ط§ط،'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ط§ظ„ط¨ط±ظٹط¯ ط§ظ„ط¥ظ„ظƒطھط±ظˆظ†ظٹ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='ط±ظ‚ظ… ط§ظ„ظ‡ط§طھظپ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='registration_steps_content',
            field=models.TextField(blank=True, help_text='ظ…ط\xadطھظˆظ‰ HTML ظٹط¸ظ‡ط± ظپظٹ ط¬ظ…ظٹط¹ طµظپط\xadط§طھ ط§ظ„ط¬ط§ظ…ط¹ط§طھ (ظٹط¯ط¹ظ… HTML)', verbose_name='ظ…ط\xadطھظˆظ‰ ط®ط·ظˆط§طھ ط§ظ„طھط³ط¬ظٹظ„'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='registration_steps_title',
            field=models.CharField(default='ط®ط·ظˆط§طھ ط§ظ„طھط³ط¬ظٹظ„', help_text='ط§ظ„ط¹ظ†ظˆط§ظ† ط§ظ„ط°ظٹ ظٹط¸ظ‡ط± ظپظٹ ط¬ظ…ظٹط¹ طµظپط\xadط§طھ ط§ظ„ط¬ط§ظ…ط¹ط§طھ', max_length=200, verbose_name='ط¹ظ†ظˆط§ظ† ظ‚ط³ظ… ط®ط·ظˆط§طھ ط§ظ„طھط³ط¬ظٹظ„'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, verbose_name='ظˆطµظپ ط§ظ„ظ…ظˆظ‚ط¹'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='ط¨ظˆط§ط¨ط§طھ ط§ظ„ط¹ظ„ظˆظ…', max_length=200, verbose_name='ط§ط³ظ… ط§ظ„ظ…ظˆظ‚ط¹'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='طھط§ط±ظٹط® ط§ظ„طھط\xadط¯ظٹط«'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='ط±ظ‚ظ… WhatsApp'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='طھط§ط±ظٹط® ط§ظ„ط¥ظ†ط´ط§ط،'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'ظ…ط³ط¤ظˆظ„ ط§ظ„ظ†ط¸ط§ظ…'), ('content_admin', 'ظ…ط³ط¤ظˆظ„ ط§ظ„ظ…ط\xadطھظˆظ‰'), ('seo_admin', 'ظ…ط³ط¤ظˆظ„ SEO')], default='content_admin', help_text='ط¯ظˆط± ط§ظ„ظ…ط³طھط®ط¯ظ… ظپظٹ ظ„ظˆط\xadط© ط§ظ„طھط\xadظƒظ…', max_length=20, verbose_name='ط§ظ„ط¯ظˆط±'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='طھط§ط±ظٹط® ط§ظ„طھط\xadط¯ظٹط«'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ط§ظ„ظ…ط³طھط®ط¯ظ…'),
        ),
    ]
