# Generated by Django 4.2.11 on 2026-06-05 14:45

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_alter_sitesettings_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'إعدادات الموقع', 'verbose_name_plural': 'إعدادات الموقع'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'ملف المستخدم', 'verbose_name_plural': 'ملفات المستخدمين'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='registration_steps_content',
            field=models.TextField(blank=True, help_text='محتوى HTML يظهر في جميع صفحات الجامعات (يدعم HTML)', verbose_name='محتوى خطوات التسجيل'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='registration_steps_title',
            field=models.CharField(default='خطوات التسجيل', help_text='العنوان الذي يظهر في جميع صفحات الجامعات', max_length=200, verbose_name='عنوان قسم خطوات التسجيل'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, verbose_name='وصف الموقع'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='بوابات العلوم', max_length=200, verbose_name='اسم الموقع'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم WhatsApp'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مسؤول النظام'), ('content_admin', 'مسؤول المحتوى'), ('seo_admin', 'مسؤول SEO')], default='content_admin', help_text='دور المستخدم في لوحة التحكم', max_length=20, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('file', models.ImageField(upload_to=apps.core.models.media_upload_path)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=500, verbose_name='النص البديل')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='عنوان الصورة')),
                ('source_type', models.CharField(choices=[('editor', 'محرر المحتوى'), ('university_logo', 'شعار جامعة'), ('university_image', 'صورة جامعة'), ('institute_image', 'صورة معهد'), ('major_image', 'صورة تخصص'), ('article_image', 'صورة مقالة')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف وسائط',
                'verbose_name_plural': 'ملفات الوسائط',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type'], name='core_mediaf_source__291d9f_idx'), models.Index(fields=['content_type', 'object_id'], name='core_mediaf_content_ee6ac0_idx'), models.Index(fields=['alt_text'], name='core_mediaf_alt_tex_817c52_idx')],
            },
        ),
    ]
