# Generated by Django 4.2.11 on 2026-06-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesettings_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='caption',
            field=models.TextField(blank=True, help_text='نص مرئي يظهر للزوار أسفل الصورة - مفيد للسياق والـ SEO', max_length=300, verbose_name='التسمية التوضيحية (Caption)'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='description',
            field=models.TextField(blank=True, help_text='وصف تفصيلي للاستخدام الداخلي وإدارة المكتبة', verbose_name='وصف داخلي'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='alt_text',
            field=models.CharField(blank=True, help_text='الأهم للـ SEO - وصف دقيق للصورة (80-140 حرف مثالي)', max_length=500, verbose_name='النص البديل (Alt Text)'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='title',
            field=models.CharField(blank=True, help_text='يظهر عند التمرير على الصورة', max_length=500, verbose_name='عنوان الصورة (Title)'),
        ),
    ]
