# Generated by Django 4.2.11 on 2026-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mediafile_caption_mediafile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, help_text='رابط الصورة في الموقع القديم (لمنع التكرار)', max_length=1000, verbose_name='رابط المصدر الأصلي'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['source_url'], name='core_mediaf_source__f10b25_idx'),
        ),
    ]
