# Generated by Django 4.2.11 on 2026-06-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mediafile_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_ga4',
            field=models.BooleanField(default=True, help_text='تفعيل/إيقاف تتبع Google Analytics', verbose_name='تفعيل Google Analytics'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, help_text='معرف GA4 (مثال: G-XXXXXXXXXX) - يُستخدم لتتبع الزوار', max_length=50, verbose_name='Google Analytics 4 Measurement ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='كود التحقق من Google Search Console', max_length=100, verbose_name='Google Site Verification Code'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sitemap_last_generated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر توليد لخريطة الموقع'),
        ),
    ]
