# Generated by Django 5.2.15 on 2026-06-29 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_add_seo_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('client_token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Lock',
                'verbose_name_plural': 'Content Locks',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_conten_content_e2ccbc_idx'), models.Index(fields=['expires_at'], name='core_conten_expires_3ac372_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
