# Generated by Django 5.2.15 on 2026-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contentlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='source_type',
            field=models.CharField(choices=[('editor', 'محرر المحتوى'), ('university_logo', 'شعار جامعة'), ('university_image', 'صورة جامعة'), ('institute_logo', 'شعار معهد'), ('institute_image', 'صورة معهد'), ('major_image', 'صورة تخصص'), ('article_image', 'صورة مقالة')], max_length=30),
        ),
    ]
