# Generated by Django 5.2.15 on 2026-07-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mediafile_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_bypass_ips',
            field=models.TextField(blank=True, help_text='أدخل عناوين IP المسموح لها بتصفح الموقع مفصولة بأسطر أو فواصل (مثال: 127.0.0.1)', verbose_name='عناوين IP المستثناة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_bypass_staff',
            field=models.BooleanField(default=True, help_text='عند التفعيل، يمكن للمستخدمين المسجلين دخولهم كـ Staff تصفح الموقع بشكل طبيعي', verbose_name='السماح لمدراء الموقع بالتصفح'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_estimated_end',
            field=models.DateTimeField(blank=True, help_text='تحديد موعد الانتهاء يعرض عداداً تنازلياً ويساعد محركات البحث في جدولة الزيارة القادمة', null=True, verbose_name='موعد الانتهاء المتوقع'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(default='الموقع قيد الصيانة حالياً لتقديم تجربة أفضل. سنعود قريباً.', verbose_name='رسالة صفحة الصيانة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='إغلاق الموقع للزوار وعرض صفحة الصيانة', verbose_name='تفعيل وضع الصيانة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_title',
            field=models.CharField(default='صيانة مجدولة', max_length=200, verbose_name='عنوان صفحة الصيانة'),
        ),
    ]
