# Generated by Django 5.2.15 on 2026-07-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_maintenance_bypass_ips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_from_address',
            field=models.EmailField(blank=True, default='noreply@example.com', help_text='البريد الذي سيظهر للمستلمين كمستلم للرسالة (مثال: noreply@sciencesgates.com)', max_length=254, verbose_name='بريد المرسل الافتراضي'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', help_text='عنوان خادم SMTP الخاص بمزود الخدمة (مثال لـ Google Workspace: smtp.gmail.com)', max_length=255, verbose_name='خادم SMTP'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_smtp_password',
            field=models.CharField(blank=True, help_text='كلمة مرور الحساب. في حالة استخدام Google Workspace، يرجى إنشاء واستخدام كلمة مرور تطبيق (App Password).', max_length=255, verbose_name='كلمة مرور SMTP'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_smtp_port',
            field=models.PositiveIntegerField(default=587, help_text='المنفذ المستخدم للإرسال (مثال: 587 للـ TLS أو 465 للـ SSL)', verbose_name='منفذ SMTP'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_smtp_use_dynamic',
            field=models.BooleanField(default=False, help_text='عند التفعيل، سيقوم النظام بإرسال رسائل البريد الإلكتروني باستخدام هذه الإعدادات بدلاً من الإعدادات الافتراضية في ملف .env', verbose_name='تفعيل إعدادات SMTP مخصصة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='تأمين الاتصال باستخدام SSL (مستحسن ومطلوب للمنفذ 465)', verbose_name='تفعيل SSL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_smtp_use_tls',
            field=models.BooleanField(default=True, help_text='تأمين الاتصال باستخدام TLS (مستحسن ومطلوب للمنفذ 587)', verbose_name='تفعيل TLS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_smtp_user',
            field=models.CharField(blank=True, help_text='البريد الإلكتروني بالكامل المستخدم لتسجيل الدخول (مثال: mail@sciencesgates.com)', max_length=255, verbose_name='اسم مستخدم SMTP'),
        ),
    ]
