# Generated by Django 5.2.15 on 2026-07-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_email_from_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email_smtp_password',
            field=models.CharField(blank=True, help_text='كلمة مرور الحساب. في حالة استخدام Google Workspace، يرجى إنشاء واستخدام كلمة مرور تطبيق (App Password).', max_length=1000, verbose_name='كلمة مرور SMTP'),
        ),
    ]
