# Generated by Django 5.2.15 on 2026-07-19

from django.db import migrations

def fix_passwords(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    from apps.core.utils import SMTPCryptography
    
    settings_obj = SiteSettings.objects.first()
    if settings_obj and settings_obj.email_smtp_password:
        val = settings_obj.email_smtp_password
        last_valid_val = val
        # Decrypt recursively to find the original plaintext password
        while True:
            try:
                decrypted = SMTPCryptography.decrypt(val)
                if not decrypted or decrypted == val:
                    break
                last_valid_val = decrypted
                val = decrypted
            except Exception:
                break
        
        # If we successfully found the plaintext password, encrypt it exactly once
        if last_valid_val and last_valid_val != settings_obj.email_smtp_password:
            # Note: We encrypt using the current settings.SECRET_KEY via the helper
            settings_obj.email_smtp_password = SMTPCryptography.encrypt(last_valid_val)
            settings_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_sitesettings_email_smtp_password'),
    ]

    operations = [
        migrations.RunPython(fix_passwords),
    ]
