# Generated by Django 5.2.15 on 2026-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_multi_encrypted_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receive_inquiry_emails',
            field=models.BooleanField(default=True, help_text='تفعيل استقبال إشعارات الاستفسارات الجديدة عبر البريد الإلكتروني', verbose_name='استقبال إيميلات الاستفسارات'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_registration_emails',
            field=models.BooleanField(default=True, help_text='تفعيل استقبال إشعارات طلبات التسجيل الجديدة عبر البريد الإلكتروني', verbose_name='استقبال إيميلات التسجيل'),
        ),
    ]
