# Generated by Django 5.2.15 on 2026-07-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_update_site_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA4CachedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(unique=True, verbose_name='عدد الأيام')),
                ('payload', models.JSONField(verbose_name='بيانات التقرير')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تقرير GA4 مخزن مؤقتاً',
                'verbose_name_plural': 'تقارير GA4 مخزنة مؤقتاً',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ga4_property_id',
            field=models.CharField(blank=True, help_text='معرف الخاصية الرقمي في GA4 (مثال: 448834920) - يُسخدم لجلب بيانات التقارير', max_length=50, verbose_name='Google Analytics 4 Property ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, help_text='معرف GA4 (مثال: G-XXXXXXXXXX) - يُسخدم لتتبع الزوار', max_length=50, verbose_name='Google Analytics 4 Measurement ID'),
        ),
    ]
