# Generated by Django 5.2.15 on 2026-07-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ga4cachedreport_sitesettings_ga4_property_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sitemap_gsc_status',
            field=models.CharField(default='لم يتم الإرسال بعد', max_length=255, verbose_name='حالة الإرسال لمحرك بحث جوجل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sitemap_last_submitted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر إرسال لخريطة الموقع لجوجل'),
        ),
    ]
