# Generated by Django 5.2.15 on 2026-07-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sitesettings_sitemap_gsc_status_and_more'),
        ('institutes', '0028_alter_institute_options_institute_order'),
        ('majors', '0024_alter_major_options_major_order'),
        ('universities', '0025_alter_university_options_university_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('section', models.CharField(choices=[('mega_menu_public_univ', 'القائمة الرئيسية - جامعات حكومية'), ('mega_menu_private_univ', 'القائمة الرئيسية - جامعات خاصة'), ('mega_menu_institute', 'القائمة الرئيسية - معاهد اللغة'), ('home_featured_univ', 'الصفحة الرئيسية - جامعات مميزة'), ('home_featured_institute', 'الصفحة الرئيسية - معاهد مميزة'), ('home_featured_major', 'الصفحة الرئيسية - تخصصات مميزة')], db_index=True, max_length=50, verbose_name='القسم')),
                ('slot_number', models.PositiveIntegerField(help_text='رقم الخانة (من 1 إلى الحد الأقصى للقسم)', verbose_name='رقم الخانة')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_slots', to='institutes.institute', verbose_name='المعهد')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_slots', to='majors.major', verbose_name='التخصص')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_slots', to='universities.university', verbose_name='الجامعة')),
            ],
            options={
                'verbose_name': 'تخصيص خانة قائمة',
                'verbose_name_plural': 'تخصيصات خانات القوائم',
                'ordering': ['section', 'slot_number'],
                'unique_together': {('section', 'slot_number')},
            },
        ),
    ]
