# Generated by Django 5.2.15 on 2026-07-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitenavigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='رابط فيسبوك'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='رابط انستغرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='رابط لينكد إن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='snapchat',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='رابط سناب شات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='رابط تليجرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='رابط تيك توك'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='رابط منصة X (تويتر)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='رابط يوتيوب'),
        ),
    ]
