# Generated by Django 5.2.15 on 2026-07-27 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0019_sitesettings_facebook_sitesettings_instagram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف المحتوى')),
                ('version_number', models.PositiveIntegerField(verbose_name='رقم النسخة')),
                ('data', models.JSONField(help_text='لقطة من بيانات الموديل والعلاقات المخزنة كـ JSON', verbose_name='بيانات النسخة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحفظ')),
                ('change_reason', models.CharField(blank=True, max_length=255, verbose_name='سبب التعديل')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المحتوى')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_versions', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة')),
            ],
            options={
                'verbose_name': 'نسخة محتوى',
                'verbose_name_plural': 'نسخ المحتوى',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_conten_content_16bd28_idx'), models.Index(fields=['created_at'], name='core_conten_created_fa5371_idx')],
            },
        ),
    ]
