# Generated by Django 4.2.26 on 2026-08-10 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0020_contentversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="د. محمد الكيالي",
                        max_length=200,
                        verbose_name="اسم الكاتب",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="dr-mohammad-kayali",
                        max_length=200,
                        unique=True,
                        verbose_name="رابط الكاتب",
                    ),
                ),
                (
                    "title_credentials",
                    models.CharField(
                        default="دكتوراه في علوم الحاسوب (UKM) - خبير الاستشارات التعليمية في ماليزيا",
                        max_length=250,
                        verbose_name="المؤهل واللقب المهني",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        default="مؤسس ومدير شركة بوابات العلوم للدراسة في ماليزيا. حاصل على درجة الدكتوراه في علوم الحاسوب من جامعة UKM الماليزية، يملك أكثر من 10 سنوات خبرة في تقديم الاستشارات الأكاديمية وإرشادات القبول الجامعي لأكثر من 3000 طالب عربي.",
                        verbose_name="السيرة الذاتية والخبرة",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="authors/",
                        verbose_name="صورة الكاتب",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        default="https://www.linkedin.com/in/mohammad-kayali/",
                        verbose_name="رابط لينكد إن",
                    ),
                ),
                (
                    "university_profile_url",
                    models.URLField(
                        blank=True,
                        default="https://www.ukm.my/",
                        verbose_name="رابط الملف الجامعي / الرسمي",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف الكاتب (E-E-A-T)",
                "verbose_name_plural": "ملفات الكتاب (E-E-A-T)",
            },
        ),
    ]
