# Generated by Django 5.2.17 on 2026-09-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_authorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='شركة بوابات العلوم', max_length=200, verbose_name='اسم الموقع'),
        ),
        migrations.CreateModel(
            name='GeneralFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('question', models.CharField(db_index=True, max_length=500, verbose_name='السؤال')),
                ('slug', models.SlugField(blank=True, help_text='معرف لاتيني فريد للرابط المباشر (مثل: admission-requirements). اتركه فارغاً للتوليد التلقائي.', max_length=200, unique=True, verbose_name='الرابط الدائم (Slug)')),
                ('answer', models.TextField(help_text='يدعم تنسيق HTML والروابط وعزل <bdi>', verbose_name='الإجابة')),
                ('category', models.CharField(choices=[('admissions', 'القبول والتسجيل'), ('visa', 'الفيزا والإقامة'), ('costs', 'التكاليف والمعيشة'), ('english', 'اللغة والآيلتس'), ('recognition', 'الاعتراف والاعتماد'), ('services', 'خدمات بوابات العلوم')], db_index=True, default='admissions', max_length=50, verbose_name='التصنيف')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='الترتيب')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='مميز في الصفحة الرئيسية')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='منشور')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة العامة',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_published', 'order'], name='core_genera_is_publ_68eee7_idx'), models.Index(fields=['is_published', 'is_featured', 'order'], name='core_genera_is_publ_cc8c63_idx'), models.Index(fields=['category', 'is_published', 'order'], name='core_genera_categor_e70382_idx')],
            },
        ),
    ]
