# Generated by Django 4.2.11 on 2026-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('lead_type', models.CharField(choices=[('registration', 'طلب تسجيل'), ('contact', 'استفسار')], db_index=True, max_length=20, verbose_name='نوع الرسالة')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('source_page', models.URLField(blank=True, help_text='الصفحة التي تم إرسال النموذج منها', verbose_name='صفحة المصدر')),
                ('referrer', models.URLField(blank=True, help_text='رابط المرجع (HTTP Referrer)', verbose_name='المرجع')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('utm_term', models.CharField(blank=True, max_length=100, verbose_name='UTM Term')),
                ('utm_content', models.CharField(blank=True, max_length=100, verbose_name='UTM Content')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='تم قراءتها')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'), models.Index(fields=['lead_type'], name='leads_lead_lead_ty_f6ba1c_idx'), models.Index(fields=['is_read'], name='leads_lead_is_read_16e1bd_idx'), models.Index(fields=['-created_at'], name='leads_lead_created_921505_idx'), models.Index(fields=['lead_type', '-created_at'], name='leads_lead_lead_ty_1ba554_idx'), models.Index(fields=['is_read', '-created_at'], name='leads_lead_is_read_13bed3_idx')],
            },
        ),
    ]
