# Generated by Django 5.2.15 on 2026-07-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_created_at_alter_lead_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان الإقامة'),
        ),
        migrations.AddField(
            model_name='lead',
            name='institution_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='اسم المؤسسة (الجامعة/المعهد)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='nationality',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='الجنسية'),
        ),
        migrations.AddField(
            model_name='lead',
            name='residence_country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='دولة الإقامة'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('in_progress', 'قيد المتابعة'), ('registered', 'تم التسجيل'), ('cancelled', 'ملغي / غير مهتم')], db_index=True, default='new', max_length=30, verbose_name='حالة المتابعة'),
        ),
        migrations.AddField(
            model_name='lead',
            name='study_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المرحلة الدراسية'),
        ),
    ]
