# Generated by Django 5.2.15 on 2026-07-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_address_lead_institution_name_lead_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مؤرشفة'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_archived'], name='leads_lead_is_arch_4339e4_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_archived', 'lead_type', '-created_at'], name='leads_lead_is_arch_382337_idx'),
        ),
    ]
