# Generated by Django 5.2.15 on 2026-07-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_is_archived_lead_leads_lead_is_arch_4339e4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='utm_content',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='utm_medium',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='utm_source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='utm_term',
        ),
    ]
