# Generated by Django 4.2.26 on 2026-08-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0007_remove_lead_utm_campaign_remove_lead_utm_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="privacy_consent",
            field=models.BooleanField(
                default=False, verbose_name="موافقة سياسة الخصوصية"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="privacy_consent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الموافقة على الخصوصية"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="privacy_policy_version",
            field=models.CharField(
                blank=True,
                default="1.0",
                max_length=20,
                verbose_name="إصدار سياسة الخصوصية",
            ),
        ),
    ]
