# Generated by Django 4.2.26 on 2026-08-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0008_lead_privacy_consent_lead_privacy_consent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="عنوان IP"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_campaign",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="اسم الحملة (utm_campaign)",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_content",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="محتوى الإعلان (utm_content)",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_medium",
            field=models.CharField(
                blank=True,
                help_text="مثل: cpc, story, organic, direct",
                max_length=150,
                null=True,
                verbose_name="وسيط الحملة (utm_medium)",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_source",
            field=models.CharField(
                blank=True,
                help_text="مثل: google, facebook, tiktok, instagram",
                max_length=150,
                null=True,
                verbose_name="مصدر الحملة (utm_source)",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_term",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="الكلمة المفتاحية (utm_term)",
            ),
        ),
    ]
