# Generated by Django 4.2.26 on 2026-09-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0009_lead_ip_address_lead_utm_campaign_lead_utm_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="address",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="عنوان الإقامة"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="البريد الإلكتروني"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="institution_name",
            field=models.CharField(
                blank=True,
                help_text="اسم الجامعة أو المعهد الذي تم التقديم عليه",
                max_length=200,
                null=True,
                verbose_name="المؤسسة التعليمية",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="محتوى الرسالة"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.CharField(max_length=200, verbose_name="الاسم الكامل"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الجنسية"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(max_length=50, verbose_name="رقم الهاتف"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="referrer",
            field=models.URLField(
                blank=True,
                help_text="رابط المصدر (HTTP Referrer)",
                max_length=500,
                verbose_name="المصدر",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="residence_country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="دولة الإقامة"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source_page",
            field=models.URLField(
                blank=True,
                help_text="الصفحة التي تم إرسال النموذج منها",
                max_length=500,
                verbose_name="صفحة المصدر",
            ),
        ),
    ]
