# Generated by Django 4.2.11 on 2026-05-30 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAnalysisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('analysis_report_json', models.JSONField(default=dict, verbose_name='تقرير التحليل التفصيلي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'تفاصيل تحليل SEO',
                'verbose_name_plural': 'تفاصيل تحليلات SEO',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_seoanal_content_90cb58_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='seoanalysisdetail',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_seo_analysis_detail_per_object'),
        ),
    ]
