# Generated by Django 5.2.15 on 2026-07-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page404Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True, verbose_name='المسار المطلوب')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('last_hit', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر محاولة')),
                ('referrers', models.JSONField(blank=True, default=dict, verbose_name='مصادر الزيارة (Referrers)')),
                ('user_agents', models.JSONField(blank=True, default=dict, verbose_name='المتصفحات / الأجهزة')),
            ],
            options={
                'verbose_name': 'سجل صفحة 404',
                'verbose_name_plural': 'سجلات صفحات 404',
                'ordering': ['-hits', '-last_hit'],
            },
        ),
    ]
