# Generated by Django 5.2.15 on 2026-07-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_page404log'),
    ]

    operations = [
        migrations.AddField(
            model_name='page404log',
            name='is_ignored',
            field=models.BooleanField(default=False, verbose_name='متجاهل'),
        ),
    ]
