# Generated by Django 4.2.26 on 2026-09-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0003_page404log_is_ignored"),
    ]

    operations = [
        migrations.AddField(
            model_name="page404log",
            name="daily_hits",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="الزيارات اليومية"
            ),
        ),
    ]
