# Generated by Django 4.2.11 on 2026-05-18 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(allow_unicode=True, help_text='رابط الفئة (يدعم الأحرف العربية)', max_length=200, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, help_text='وصف الفئة', verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='اسم الوسم')),
                ('slug', models.SlugField(allow_unicode=True, help_text='رابط الوسم (يدعم الأحرف العربية)', max_length=100, unique=True, verbose_name='الرابط')),
            ],
            options={
                'verbose_name': 'وسم',
                'verbose_name_plural': 'الوسوم',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('publish_status', models.CharField(choices=[('published', 'منشور'), ('unpublished', 'غير منشور')], db_index=True, default='unpublished', help_text='المحتوى المنشور فقط يظهر للزوار', max_length=20, verbose_name='حالة النشر')),
                ('meta_title', models.CharField(blank=True, help_text='يظهر في نتائج البحث (60 حرف كحد أقصى)', max_length=60, verbose_name='عنوان SEO')),
                ('meta_description', models.TextField(blank=True, help_text='يظهر في نتائج البحث (160 حرف كحد أقصى)', max_length=160, verbose_name='وصف SEO')),
                ('focus_keyword', models.CharField(blank=True, help_text='الكلمة المفتاحية الرئيسية للصفحة', max_length=100, verbose_name='الكلمة المفتاحية')),
                ('canonical_url', models.URLField(blank=True, help_text='اتركه فارغاً لاستخدام الرابط الافتراضي', verbose_name='الرابط الأساسي')),
                ('robots_index', models.BooleanField(default=True, help_text='السماح لمحركات البحث بفهرسة هذه الصفحة', verbose_name='السماح بالفهرسة')),
                ('robots_follow', models.BooleanField(default=True, help_text='السماح لمحركات البحث بتتبع الروابط في هذه الصفحة', verbose_name='السماح بتتبع الروابط')),
                ('sitemap_include', models.BooleanField(default=True, help_text='تضمين هذه الصفحة في ملف sitemap.xml', verbose_name='تضمين في خريطة الموقع')),
                ('og_title', models.CharField(blank=True, help_text='العنوان عند المشاركة على وسائل التواصل', max_length=60, verbose_name='عنوان Open Graph')),
                ('og_description', models.TextField(blank=True, help_text='الوصف عند المشاركة على وسائل التواصل', max_length=160, verbose_name='وصف Open Graph')),
                ('og_image', models.ImageField(blank=True, help_text='الصورة عند المشاركة على وسائل التواصل (1200x630 بكسل)', upload_to='og_images/', verbose_name='صورة Open Graph')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='العنوان')),
                ('slug', models.SlugField(allow_unicode=True, help_text='رابط المقالة (يدعم الأحرف العربية)', max_length=300, unique=True, verbose_name='الرابط')),
                ('featured_image', models.ImageField(help_text='الصورة الرئيسية للمقالة', upload_to='articles/images/', verbose_name='الصورة المميزة')),
                ('publish_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ النشر')),
                ('content', models.TextField(help_text='محتوى المقالة (HTML محمي)', verbose_name='المحتوى')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'مقالة',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-publish_date'],
            },
        ),
    ]
