# Generated by Django 4.2.11 on 2026-05-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_institutes',
            field=models.ManyToManyField(blank=True, related_name='articles', to='institutes.institute', verbose_name='المعاهد المرتبطة'),
        ),
    ]
