# Generated by Django 4.2.11 on 2026-05-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_universities',
            field=models.ManyToManyField(blank=True, related_name='articles', to='universities.university', verbose_name='الجامعات المرتبطة'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.tag', verbose_name='الوسوم'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-publish_date'], name='articles_ar_publish_b0da20_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', '-publish_date'], name='articles_ar_categor_b09287_idx'),
        ),
    ]
