# Generated by Django 4.2.11 on 2026-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0003_subjectstable_salarytable_countriestable'),
        ('articles', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_majors',
            field=models.ManyToManyField(blank=True, related_name='articles', to='majors.major', verbose_name='التخصصات المرتبطة'),
        ),
    ]
