# Generated by Django 4.2.11 on 2026-05-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_related_majors'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['publish_status'], name='articles_ar_publish_86d5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='articles_ar_title_ee81af_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['publish_status', '-publish_date'], name='articles_ar_publish_0137ee_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='articles_ar_author__8895b2_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='articles_ca_name_b48539_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='articles_ta_name_917d3f_idx'),
        ),
    ]
