# Generated by Django 4.2.11 on 2026-06-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_category_options_article_seo_critical_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='النص البديل للصورة المميزة للمقالة (SEO)', max_length=200, verbose_name='النص البديل للصورة المميزة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='اتركه فارغاً لاستخدام الرابط الافتراضي', verbose_name='الرابط الأساسي'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='article',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='الكلمة المفتاحية الرئيسية للصفحة', max_length=100, verbose_name='الكلمة المفتاحية'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, help_text='يظهر في نتائج البحث (160 حرف كحد أقصى)', max_length=160, verbose_name='وصف SEO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='يظهر في نتائج البحث (60 حرف كحد أقصى)', max_length=60, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_description',
            field=models.TextField(blank=True, help_text='الوصف عند المشاركة على وسائل التواصل', max_length=160, verbose_name='وصف Open Graph'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, help_text='الصورة عند المشاركة على وسائل التواصل (1200x630 بكسل)', upload_to='og_images/', verbose_name='صورة Open Graph'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, help_text='العنوان عند المشاركة على وسائل التواصل', max_length=60, verbose_name='عنوان Open Graph'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_status',
            field=models.CharField(choices=[('published', 'منشور'), ('unpublished', 'غير منشور')], db_index=True, default='unpublished', help_text='المحتوى المنشور فقط يظهر للزوار', max_length=20, verbose_name='حالة النشر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='السماح لمحركات البحث بتتبع الروابط في هذه الصفحة', verbose_name='السماح بتتبع الروابط'),
        ),
        migrations.AlterField(
            model_name='article',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='السماح لمحركات البحث بفهرسة هذه الصفحة', verbose_name='السماح بالفهرسة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sitemap_include',
            field=models.BooleanField(default=True, help_text='تضمين هذه الصفحة في ملف sitemap.xml', verbose_name='تضمين في خريطة الموقع'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
