# Generated by Django 5.2.15 on 2026-06-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_meta_title_alter_article_og_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='تفعيل هذا الخيار سيجعل الرابط مباشراً بدون بادئة الفئة (مثال: /slug/ بدلاً من /articles/slug/)', verbose_name='رابط قديم'),
        ),
    ]
