# Generated by Django 5.2.15 on 2026-07-16 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_keyphrase_synonyms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور السؤال (الأصغر أولاً)', verbose_name='ترتيب العرض')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='articles.article', verbose_name='المقالة')),
            ],
            options={
                'verbose_name': 'سؤال شائع للمقالة',
                'verbose_name_plural': 'الأسئلة الشائعة للمقالات',
                'ordering': ['sort_order'],
            },
        ),
    ]
