# Generated by Django 5.2.15 on 2026-07-16 23:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ النشر'),
        ),
    ]
