# Generated by Django 5.2.15 on 2026-07-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_similarities_a', to='articles.article')),
                ('article_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_similarities_b', to='articles.article')),
            ],
            options={
                'verbose_name': 'تشابه متجاهل',
                'verbose_name_plural': 'التشابهات المتجاهلة',
                'unique_together': {('article_a', 'article_b')},
            },
        ),
    ]
