# Generated by Django 5.2.15 on 2026-07-17 21:12

import apps.core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_ignoredsimilarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الملف')),
                ('file', models.FileField(upload_to='articles/attachments/', validators=[apps.core.utils.validate_attachment_file], verbose_name='الملف')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='articles.article', verbose_name='المقالة')),
            ],
            options={
                'verbose_name': 'ملف المقالة',
                'verbose_name_plural': 'ملفات المقالة',
                'ordering': ['-created_at'],
            },
        ),
    ]
