# Generated by Django 4.2.11 on 2026-05-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['publish_status'], name='institutes__publish_219877_idx'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['name'], name='institutes__name_445ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['publish_status', 'name'], name='institutes__publish_189603_idx'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['-created_at'], name='institutes__created_bbd091_idx'),
        ),
    ]
