# Generated by Django 4.2.11 on 2026-05-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_institute_institutes__publish_219877_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='institute_type',
            field=models.CharField(choices=[('language', 'معهد لغة إنجليزية'), ('academic', 'معهد أكاديمي')], db_index=True, default='academic', help_text='تصنيف المعهد (لغة أو أكاديمي)', max_length=20, verbose_name='نوع المعهد'),
        ),
    ]
