# Generated by Django 4.2.11 on 2026-05-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0003_institute_institute_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institute_type',
            field=models.CharField(choices=[('language', 'معهد لغة'), ('academic', 'معهد أكاديمي')], db_index=True, default='academic', help_text='تصنيف المعهد (لغة أو أكاديمي)', max_length=20, verbose_name='نوع المعهد'),
        ),
    ]
