# Generated by Django 5.2.15 on 2026-06-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0007_alter_institute_meta_title_alter_institute_og_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='تفعيل هذا الخيار سيجعل الرابط مباشراً بدون بادئة الفئة (مثال: /slug/ بدلاً من /institutes/slug/)', verbose_name='رابط قديم'),
        ),
    ]
