# Generated by Django 5.2.15 on 2026-06-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_is_legacy'),
        ('institutes', '0008_institute_is_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='institutes', to='articles.tag', verbose_name='الوسوم'),
        ),
    ]
