# Generated by Django 5.2.15 on 2026-06-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0009_institute_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='keyphrase_synonyms',
            field=models.CharField(blank=True, help_text='مرادفات للكلمة المفتاحية الرئيسية مفصولة بفواصل (، أو ,)', max_length=255, verbose_name='مرادفات الكلمة المفتاحية'),
        ),
    ]
