# Generated by Django 5.2.15 on 2026-06-26 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0010_institute_keyphrase_synonyms'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الملف')),
                ('file', models.FileField(upload_to='institutes/attachments/', verbose_name='الملف')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='institutes.institute', verbose_name='المعهد')),
            ],
            options={
                'verbose_name': 'ملف المعهد',
                'verbose_name_plural': 'ملفات المعهد',
                'ordering': ['-created_at'],
            },
        ),
    ]
