# Generated by Django 5.2.15 on 2026-06-29 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0011_instituteattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='institute_type',
        ),
        migrations.AddField(
            model_name='institute',
            name='city',
            field=models.CharField(choices=[('kl', 'كوالالمبور'), ('selangor', 'سيلانجور'), ('penang', 'بينانج'), ('johor', 'جوهور'), ('kedah', 'قدح'), ('kelantan', 'كلنتان'), ('melaka', 'ملقا'), ('negeri-sembilan', 'نيجري سمبيلان'), ('pahang', 'باهانغ'), ('perak', 'بيرق'), ('perlis', 'برليس'), ('sabah', 'صباح'), ('sarawak', 'سراوق'), ('terengganu', 'ترينجانو'), ('putrajaya', 'بوتراجايا'), ('labuan', 'لابوان'), ('cyberjaya', 'سايبرجايا')], db_index=True, default='kl', help_text='المدينة التي يقع بها المعهد لتسهيل التصفية والبحث', max_length=20, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='institute',
            name='english_study',
            field=models.TextField(blank=True, help_text='معلومات وتفاصيل عن دراسة اللغة الإنجليزية في المعهد', verbose_name='دراسة اللغة الإنجليزية'),
        ),
        migrations.AddField(
            model_name='institute',
            name='location',
            field=models.TextField(blank=True, help_text='موقع المعهد (المدينة، الولاية)', verbose_name='الموقع'),
        ),
        migrations.AddField(
            model_name='institute',
            name='telephone',
            field=models.CharField(blank=True, help_text='رقم هاتف التواصل للمعهد لتسهيل التواصل والبحث المحلي', max_length=50, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='institute',
            name='website',
            field=models.URLField(blank=True, help_text='رابط الموقع الإلكتروني الرسمي للمعهد (sameAs)', verbose_name='الموقع الرسمي للمعهد'),
        ),
        migrations.AddField(
            model_name='institute',
            name='why_choose_us',
            field=models.TextField(blank=True, help_text='أسباب اختيار الطلاب العرب للدراسة في هذا المعهد', verbose_name='لماذا يختار الطلاب العرب هذا المعهد'),
        ),
        migrations.CreateModel(
            name='InstituteFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور السؤال (الأصغر أولاً)', verbose_name='ترتيب العرض')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='institutes.institute', verbose_name='المعهد')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['sort_order'],
            },
        ),
    ]
