# Generated by Django 5.2.15 on 2026-06-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0012_remove_institute_institute_type_institute_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='telephone',
        ),
    ]
