# Generated by Django 5.2.15 on 2026-06-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0013_remove_institute_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='registration_requirements',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='registration_section',
        ),
    ]
