# Generated by Django 5.2.15 on 2026-06-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0014_remove_institute_registration_requirements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'رسوم الكورس', 'verbose_name_plural': 'جدول الرسوم'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='notes',
        ),
        migrations.AddField(
            model_name='course',
            name='fees_myr',
            field=models.CharField(default='', help_text='مثال: 3,400 MYR', max_length=100, verbose_name='التكلفة بالرنجت MYR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='fees_sar',
            field=models.CharField(blank=True, help_text='مثال: 3,216 SAR', max_length=100, verbose_name='التكلفة بالريال SAR'),
        ),
        migrations.AddField(
            model_name='course',
            name='fees_usd',
            field=models.CharField(blank=True, help_text='مثال: 857 USD', max_length=100, verbose_name='التكلفة بالدولار USD'),
        ),
        migrations.AddField(
            model_name='course',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='ترتيب عرض الصف (الأصغر أولاً)', verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='course',
            name='visa_duration',
            field=models.CharField(blank=True, help_text='مثال: بدون تأشيرة، 6 أشهر، سنة', max_length=100, verbose_name='مدة تأشيرة الطالب'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text='مثال: شهر، شهرين، 3 أشهر', max_length=100, verbose_name='مدة الكورس'),
        ),
    ]
