# Generated by Django 5.2.15 on 2026-06-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0015_alter_course_options_remove_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='telephone',
            field=models.CharField(blank=True, help_text='رقم هاتف التواصل للمعهد لتسهيل التواصل والبحث المحلي', max_length=50, verbose_name='رقم الهاتف'),
        ),
    ]
