# Generated by Django 5.2.15 on 2026-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0016_institute_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='introduction',
            field=models.TextField(blank=True, help_text='مقدمة اختيارية تظهر في بداية صفحة المعهد', verbose_name='المقدمة'),
        ),
    ]
