# Generated by Django 5.2.15 on 2026-06-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0018_institute_state_alter_institute_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='state',
            field=models.CharField(choices=[('kl', 'كوالالمبور'), ('selangor', 'سيلانجور'), ('penang', 'بينانج'), ('johor', 'جوهور'), ('kedah', 'قدح'), ('kelantan', 'كلنتان'), ('melaka', 'ملقا'), ('negeri-sembilan', 'نيجري سمبيلان'), ('pahang', 'باهانغ'), ('perak', 'بيرق'), ('perlis', 'برليس'), ('sabah', 'صباح'), ('sarawak', 'سراوق'), ('terengganu', 'ترينجانو'), ('putrajaya', 'بوتراجايا'), ('labuan', 'لابوان')], db_index=True, default='kl', help_text='الولاية التي يقع بها المعهد لتسهيل التصفية والبحث', max_length=20, verbose_name='الولاية'),
        ),
    ]
