# Generated by Django 5.2.15 on 2026-07-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0019_alter_institute_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='fees_excludes',
            field=models.TextField(blank=True, default='', help_text='ما لا تشمله الرسوم الموضحة (مثال: المصروف الشخصي، السكن...)', verbose_name='الرسوم لا تشمل'),
        ),
        migrations.AddField(
            model_name='institute',
            name='fees_includes',
            field=models.TextField(blank=True, default='', help_text='ما تشمله الرسوم الموضحة (مثال: تكاليف الدراسة، ورسوم تأشيرة الطالب...)', verbose_name='الرسوم تشمل'),
        ),
    ]
