# Generated by Django 5.2.15 on 2026-07-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0021_populate_fees_includes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('regular', 'كورس عادي (4 ساعات في اليوم)'), ('intensive', 'كورس مكثف (5 ساعات في اليوم)')], default='regular', max_length=50, verbose_name='نوع الكورس'),
        ),
    ]
