# Generated by Django 5.2.15 on 2026-07-01 23:28

from django.db import migrations, models


def make_existing_courses_undefined(apps, schema_editor):
    Course = apps.get_model('institutes', 'Course')
    Course.objects.filter(course_type='regular').update(course_type='undefined')


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0022_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('regular', 'كورس عادي (4 ساعات في اليوم)'), ('intensive', 'كورس مكثف (5 ساعات في اليوم)'), ('super_intensive', 'كورس مكثف (6 ساعات في اليوم)'), ('undefined', 'بدون تحديد ساعات')], default='undefined', max_length=50, verbose_name='نوع الكورس'),
        ),
        migrations.RunPython(make_existing_courses_undefined, reverse_code=migrations.RunPython.noop),
    ]
