# Generated by Django 5.2.15 on 2026-07-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0023_alter_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('regular', 'كورس (4 ساعات / يوم)'), ('intensive', 'كورس (5 ساعات / يوم)'), ('super_intensive', 'كورس (6 ساعات / يوم)'), ('undefined', 'بدون تحديد ساعات')], default='undefined', max_length=50, verbose_name='نوع الكورس'),
        ),
    ]
