# Generated by Django 5.2.15 on 2026-07-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0024_alter_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('regular', '4 ساعات'), ('intensive', '5 ساعات'), ('super_intensive', '6 ساعات'), ('undefined', 'بدون ساعات')], default='undefined', max_length=50, verbose_name='نوع الكورس'),
        ),
    ]
