# Generated by Django 5.2.15 on 2026-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0025_alter_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, help_text='شعار المعهد (PNG مع خلفية شفافة مفضل)', null=True, upload_to='institutes/logos/', verbose_name='شعار المعهد'),
        ),
        migrations.AddField(
            model_name='institute',
            name='logo_alt',
            field=models.CharField(blank=True, help_text='النص البديل لشعار المعهد (SEO)', max_length=200, verbose_name='النص البديل للشعار'),
        ),
    ]
