# Generated by Django 5.2.15 on 2026-07-17 21:12

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0026_institute_logo_institute_logo_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteattachment',
            name='file',
            field=models.FileField(upload_to='institutes/attachments/', validators=[apps.core.utils.validate_attachment_file], verbose_name='الملف'),
        ),
    ]
