# Generated by Django 5.2.15 on 2026-07-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0027_alter_instituteattachment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute',
            options={'ordering': ['order', 'name'], 'verbose_name': 'معهد', 'verbose_name_plural': 'المعاهد'},
        ),
        migrations.AddField(
            model_name='institute',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='ترتيب ظهور المعهد في صفحات القوائم (الأصغر أولاً)', verbose_name='ترتيب العرض'),
        ),
    ]
