# Generated by Django 4.2.26 on 2026-08-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0028_alter_institute_options_institute_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="institute",
            name="min_course_fee_usd",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="الحد الأدنى التقديري للرسوم بالدولار الأمريكي (USD) لعرضها في البطاقات ومقتطفات جوجل.",
                null=True,
                verbose_name="الحد الأدنى للرسوم بالدولار",
            ),
        ),
    ]
